name: Main Taski Workflow
on:
  push:
    branches:
      - main
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Проверяем код
        uses: actions/checkout@v3
      
      - name: Готовим python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Устанавливаем зависимости
        run: |
          python -m pip install --upgrade pip 
          pip install flake8==6.0.0 flake8-isort==6.0.0

      - name: Тестируем через flake8
        run: python -m flake8 backend/ 